#GrpcAddr: 127.0.0.1:8989
#log:
#  file: 1
log:
#  level: 1

#prods:
#  acl:
#    1: 127.0.0.1:8083
#  pass:
#    1: 127.0.0.1:8083
#msg:
#  LastUri: absir:absir@(127.0.0.1)/axj-gw?charset=utf8mb4&loc=Local